[package]
name = "colo_rs"
version = "0.1.0"
authors = ["FelixRilling <contact@rilling.dev>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
termcolor = "1.1.2"

[dev-dependencies]
float-cmp = "0.8.0"
