[package]
name = "color-utils-cli"
version = "0.1.0"
authors = ["FelixRilling <contact@rilling.dev>"]
edition = "2018"

[[bin]]
name = "colu"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-utils = { version = "0.1.0", path = "../lib" }

rug = "1.12.0"

log = "0.4.14"
stderrlog = "0.5.1"

clap = "2.33.3"

termcolor = "1.1.2"
