[package]
name = "color-utils-cli"
version = "0.1.0"
authors = ["FelixRilling <contact@rilling.dev>"]
description = """
Binary for command line usage of color-utils.
"""
edition = "2021"

[[bin]]
name = "colu"
path = "src/main.rs"

[dependencies]
color-utils-internal = { version = "0.2.0", path = "../internal" }
color-utils = { version = "0.2.0", path = "../lib" }

log = "0.4.16"
env_logger = "0.9.0"
clap = "2.34.0"
termcolor = "1.1.3"

[dependencies.palette]
version = "0.6.0"
default-features = false
features = ["std"]
