[package]
name = "color-utils-cli"
version = "0.1.0"
authors = ["FelixRilling <contact@rilling.dev>"]
description = """
Binary for command line usage of color-utils.
"""
edition = "2018"

[[bin]]
name = "colu"
path = "src/main.rs"

[dependencies]
color-utils-internal = { version = "0.2.0", path = "../internal" }
color-utils = { version = "0.2.0", path = "../lib" }

log = "0.4.14"
env_logger = "0.8.4"
clap = "2.33.3"
termcolor = "1.1.2"

[dependencies.rug]
version = "1.12"
default-features = false
features = ["float"]
