[package]
name = "color-utils-internal"
version = "0.2.0"
authors = ["FelixRilling <contact@rilling.dev>"]
description = """
Internal cross-crate utility code.
"""
edition = "2021"

[dependencies]
num-traits = "0.2.15"
