name: Tests

on:
    push:
        branches: [ development, main ]
    pull_request:
        branches: [ development ]

jobs:
    test:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3
            -   uses: actions-rs/toolchain@v1
                with:
                    toolchain: stable
                    components: clippy
            -   uses: actions-rs/clippy-check@v1
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
            -   run: cargo test
